name: Generate GitHub Stats Cards

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-cards
    permissions:
      contents: write # Esta é a linha que resolve o erro 128!
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.STATS_TOKEN }}
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.STATS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
